### ISSUE TITLE
Add data loading failed designs into Stats

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/stats#85]
- [x] Design Required
- [ ] Development

**Comment by erikatruscott-ux** [comment]
Currently, the user has no call to action to reload a page (or panel) if the data failed to load.

Here are two solutions:
1. An empty state for the boxes/containers when we have failed to load the data. (2 Large, 2 Small, and a tooltip)
https://www.figma.com/file/ddnq2wCdPeIbRsMmnkyj0z/Stats-User-Flows?node-id=958%3A299

2. A toast/notification, appearing the top right corner, and allows the user to manually click to try to re-load.
https://www.figma.com/file/ddnq2wCdPeIbRsMmnkyj0z/Stats-User-Flows?node-id=969%3A20

3. A quick prototype to show how it might work.
